### ISSUE TITLE
Bought wrong pattern

### ISSUE THREAD

**Issue by rabume** [sotolko/csgo-market-sniper#16]
It bought the wrong patterns:

``` yaml
skins:
  - url: https://steamcommunity.com/market/listings/730/AWP%20%7C%20PAW%20%28Factory%20New%29
    float: 
    price: 7
    number_of_stickers: 
    pages: 3
    pattern: 420
  - url: https://steamcommunity.com/market/listings/730/Five-SeveN%20%7C%20Kami%20%28Factory%20New%29
    float: 
    price: 2
    number_of_stickers:
    pages: 10
    pattern: 909
  - url: https://steamcommunity.com/market/listings/730/StatTrak%E2%84%A2%20Five-SeveN%20%7C%20Kami%20%28Factory%20New%29
    float: 
    price: 6
    number_of_stickers:
    pages: 4
    pattern: 909
```

![image](https://user-images.githubusercontent.com/19410629/232615074-d948e908-d4cd-4b09-8eb3-c008ad257aa4.png)

Is my config wrong?
